# hi there from Xavier

[hekad]
maxprocs = 2

[ScampInput]
Name = "logging"
Listen = "0.0.0.0:30100"
Decoder = "LogPayloadDecoder"
[ScampInput.handler.0]
Action = "Logger.log" # the action's name (sent out in announcements)
Logger = "logsink" # the 'Logger' value on the internal heka message. Used for internal routing.

[LogPayloadDecoder]
type = "SandboxDecoder"
filename = "/etc/heka/lua_decoders/scamp_log_payload_decoder.lua"

[StatAccumInput]

# Heka dashboard for internal metrics and time series graphs
[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 15

# Before
[ESJsonEncoder]
index = "%{Hostname}-%{%Y.%m.%d}"
es_index_from_timestamp = true
type_name = "%{Type}" # hostname is just being used to stash the index name from the lua decoder. scamp doesn't preserve source so this is safe, right?
fields = ["Timestamp", "Logger", "DynamicFields" ]
    [ESJsonEncoder.field_mappings]
    Timestamp = "timestamp"
    Severity = "level"

[ElasticSearchOutput]
message_matcher = "Logger == 'logsink'"
server = "http://localhost:9200" # TODO: this needs config injection
encoder = "ESJsonEncoder"
flush_interval = 1000
flush_count = 5

# Just in case you want to see the JSON sent to elasticsearch
# [LogOutput]
# message_matcher = "Logger == 'logsink'"
# encoder = "ESJsonEncoder"
